# URL
url: https://weisiwu.github.io/

# Header
menu:
  首页: /
  前端: /tags/frontend
  os: /tags/linux
  软件: /tags/software
  关于: /tags/about

# Content
excerpt_link: 阅读更多

# Sidebar
author:
  name: 卫某人
  work: 青青草原放羊娃
  location: 青青草原
  avatar_url: /images/avatar.png

# Links:
links:
  - svg: ./source/svg/github.svg
    url: https://github.com/weisiwu
  - svg: ./source/svg/segmentfault.svg
    url: https://segmentfault.com/u/javascriptuser
  - svg: ./source/svg/zhihu.svg
    url: https://www.zhihu.com/people/wei-si-wu/activities
  - svg: ./source/svg/twitter.svg
    url: https://twitter.com/weisiwu

# github comment 
git_commit:
  enable: true
  client_id: c3af3992520bacebd1c9
  client_secret: 68a9cac186eb0d7239f42203e5727428ef047a7e
  repo: weisiwu.github.io
  owner: weisiwu
  admin:
    - weisiwu
  per_page: 10

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico


# hexo-excerpt plugins
## https://chekun.me/post/hexo-excerpt/
excerpt:
  depth: 1
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true